rafter-controller-manager:
  enabled: true

  image:
    repository: eu.gcr.io/kyma-project/rafter-controller-manager
    tag: d999a403
    pullPolicy: IfNotPresent

  installCRDs: true

  pod:
    resources:
      limits:
        cpu: 150m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 32Mi
    volumes:
      - name: tmp-empty-dir
        emptyDir: {}
    volumeMounts:
      - mountPath: /tmp
        name: tmp-empty-dir
    extraProperties:
      terminationGracePeriodSeconds: 10

  webhooksConfigMap:
    create: true
    name: rafter-webhooks-cfg
    namespace: "{{ .Release.Namespace }}"
    hooks:
      markdown: |-
        {
          "metadataExtractors":[
            {
              "name": "{{ .Release.Name }}-rafter-front-matter-service",
              "namespace": "{{ .Release.Namespace }}",
              "endpoint": "/v1/extract",
              "filter": "\\.md$"
            }
          ]
        }
      asyncapi: |-
        {
          "validations":[
            {
              "name": "{{ .Release.Name }}-rafter-asyncapi-service",
              "namespace": "{{ .Release.Namespace }}",
              "endpoint": "/v1/validate"
            }
          ],
          "mutations":[
            {
              "name": "{{ .Release.Name }}-rafter-asyncapi-service",
              "namespace": "{{ .Release.Namespace }}",
              "endpoint": "/v1/convert"
            }
          ]
        }

  envs:
    clusterAssetGroup:
      relistInterval:
        value: 5m
    assetGroup:
      relistInterval:
        value: 5m
    clusterBucket:
      relistInterval:
        value: 30s
      maxConcurrentReconciles:
        value: "1"
      region:
        value: us-east-1
    bucket:
      relistInterval:
        value: 30s
      maxConcurrentReconciles:
        value: "1"
      region:
        value: us-east-1
    clusterAsset:
      relistInterval:
        value: 30s
      maxConcurrentReconciles:
        value: "1"
    asset:
      relistInterval:
        value: 30s
      maxConcurrentReconciles:
        value: "1"
    store:
      endpoint:
        value: "{{ .Release.Name }}-minio.{{ .Release.Namespace }}.svc.cluster.local:9000"
      externalEndpoint:
        value: "http://{{ .Release.Name }}-minio.{{ .Release.Namespace }}.svc.cluster.local:9000"
      accessKey:
        valueFrom:
          secretKeyRef:
            name: "{{ .Release.Name }}-minio"
            key: accesskey
      secretKey:
        valueFrom:
          secretKeyRef:
            name: "{{ .Release.Name }}-minio"
            key: secretkey
      useSSL:
        value: "false"
      uploadWorkers:
        value: "10"
    loader:
      verifySSL:
        value: "false"
      tempDir:
        value: "/tmp"
    webhooks:
      validation:
        timeout:
          value: 1m
        workers:
          value: "10"
      mutation:
        timeout:
          value: 1m
        workers:
          value: "10"
      metadata:
        timeout:
          value: 1m

  minio:
    enabled: true

    accessKey: ""
    secretKey: ""

    image:
      tag: RELEASE.2019-06-04T01-15-58Z

    persistence:
      enabled: true
      size: 10Gi

    podAnnotations:
      persistence: "on"

    DeploymentUpdate:
      type: Recreate

    environment:
      MINIO_BROWSER: "off"
      MINIO_PROMETHEUS_AUTH_TYPE: "public"

    defaultBucket:
      enabled: false

    resources:
      requests:
        memory: 32Mi
        cpu: 10m
      limits:
        memory: 128Mi
        cpu: 100m

rafter-upload-service:
  enabled: true

  minio:
    enabled: false
    persistence:
      enabled: true
      size: 10Gi
    podAnnotations:
      persistence: "on"

  image:
    repository: eu.gcr.io/kyma-project/rafter-upload-service
    tag: d999a403
    pullPolicy: IfNotPresent

  pod:
    extraProperties: {}
  envs:
    verbose:
      value: "false"
    upload:
      timeout:
        value: "30m"
      workers:
        value: "10"
      endpoint:
        value: "{{ .Release.Name }}-minio.{{ .Release.Namespace }}.svc.cluster.local"
      externalEndpoint:
        value: "http://{{ .Release.Name }}-minio.{{ .Release.Namespace }}.svc.cluster.local:9000"
      port:
        value: "9000"
      accessKey:
        valueFrom:
          secretKeyRef:
            name: "{{ .Release.Name }}-minio"
            key: accesskey
      secretKey:
        valueFrom:
          secretKeyRef:
            name: "{{ .Release.Name }}-minio"
            key: secretkey
      secure:
        value: "false"
    bucket:
      privatePrefix:
        value: system-private
      publicPrefix:
        value: system-public
      region:
        value: "us-east-1"
    configMap:
      enabled:
        value: "true"
      name:
        value: "rafter-upload-service"
      namespace:
        value: "{{ .Release.Namespace }}"

  migrator:
    images:
      alpineKubectl:
        repository: eu.gcr.io/kyma-project/test-infra/alpine-kubectl
        tag: "v20190325-ff66a3a"
        pullPolicy: IfNotPresent
      minioClient:
        repository: "minio/mc"
        tag: "RELEASE.2019-04-03T17-59-57Z"
        pullPolicy: IfNotPresent
    pre:
      minioDeploymentRefName:
      minioSecretRefName:
    post:
      minioSecretRefName:

rafter-front-matter-service:
  enabled: true

  image:
    repository: eu.gcr.io/kyma-project/rafter-front-matter-service
    tag: d999a403
    pullPolicy: IfNotPresent

  pod:
    extraProperties: {}

  envs:
    verbose:
      value: "false"
    timeout:
      value: "1m"
    workers:
      value: "10"

rafter-asyncapi-service:
  enabled: true

  image:
    repository: eu.gcr.io/kyma-project/rafter-asyncapi-service
    tag: d999a403
    pullPolicy: IfNotPresent

  pod:
    extraProperties: {}
  envs:
    verbose:
      value: "false"
